name: dextrous_crm_new2
description: Dextrous CRM

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.6.1+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^2.0.0
  kf_drawer: ^0.0.2
  dio: 2.0.22
  http: 0.12.0
  modal_progress_hud: ^0.1.3
  bubble_tab_indicator: "^0.1.4"
  bottom_navy_bar: ^3.0.0
  flutter_statusbar : ^0.0.1
  flutter_html: ^0.11.1
  flutter_datetime_picker: ^1.2.8
  battery: ^0.3.1+1
  shared_preferences: "0.5.3+5"
  fluttertoast: ^3.1.3
  progress_dialog: ^1.2.0
  geolocator: ^5.1.4+2
  url_launcher: ^5.2.5
  maps_launcher: ^1.0.1
  connectivity: ^0.4.5+7
  month_picker_dialog: ^0.3.0
  autocomplete_textfield: ^1.6.4
  flutter_multiselect: 0.0.1
  multiselect_formfield: ^0.1.2
  toggle_button: ^1.0.1
  indexed_list_view: ^1.0.8
  flutter_widgets: ^0.1.7
  image_picker_saver: ^0.3.0








dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/card_background.png
    - assets/images/background.png
    - assets/images/c1.png
    - assets/images/h.png
    - assets/images/i.png
    - assets/images/back.png
    - assets/images/leads2.png
    - assets/images/leads1.png
    - assets/images/status.png
    - assets/images/status_click.png
    - assets/images/comment-off.png
    - assets/images/comment-on.png
    - assets/images/contact-off.png
    - assets/images/contact-on.png
    - assets/images/summary-off.png
    - assets/images/summary-on.png
    - assets/images/check.png
    - assets/images/check2.png
    - assets/images/comments.png
    - assets/images/comments2.png
    - assets/images/meting.png
    - assets/images/call.png
    - assets/images/callsa.png
    - assets/images/go.png
    - assets/images/happy.png
    - assets/images/sad.png
    - assets/images/switch_off.png
    - assets/images/call_close.png
    - assets/images/call_close1.png
    - assets/images/call_meeting.png
    - assets/images/call_meeting1.png
    - assets/images/call_route.png
    - assets/images/call_route1.png
    - assets/images/switch_on.png
    - assets/images/sad.png
    - assets/images/sad1.png
    - assets/images/happy.png
    - assets/images/happy1.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
